### ISSUE TITLE
不能正常上传负载和用户流量数据

### ISSUE THREAD

**Issue by eeeeLeeee** [rico93/v2ray-sspanel-v3-mod_Uim-plugin#1]
用户数量：1K-1.5K
故障：不能正常上传负载和用户流量数据
log里貌似是cron炸了
```
2019/02/18 14:32:47 [Info] SSPanelPlugin: now begin to check users
2019/02/18 14:33:46 [Info] SSPanelPlugin: old node info xxxxx;xx;16;ws;;path=/v1|host=jd.hk 
2019/02/18 14:33:46 [Info] SSPanelPlugin: new node info xxxxx;xx;16;ws;;path=/v1|host=jd.hk
2019/02/18 14:33:46 [Info] SSPanelPlugin: now begin to check users
2019/02/18 14:33:46 cron: panic running job: assignment to entry in nil map
goroutine 63039 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc0045e05f0)
        github.com/robfig/cron/cron.go:161 +0xbc
panic(0xaff9c0, 0xcab450)
        /go/src/runtime/panic.go:513 +0x1b9
github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/Manager.(*Manager).Remove(...)
        github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/Manager/Manager.go:41
github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin.(*Panel).updateManager(0xc00008f210)
        github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/panel.go:99 +0x9ab
github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin.(*Panel).do(0xc00008f210, 0xc025290e80, 0x429fe1)
        github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/panel.go:55 +0x2b
github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin.(*Panel).Start.func1()
        github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/panel.go:39 +0x2e
github.com/robfig/cron.FuncJob.Run(0xc00008f230)
        github.com/robfig/cron/cron.go:92 +0x25
github.com/robfig/cron.(*Cron).runWithRecovery(0xc0045e05f0, 0xcb1640, 0xc00008f230)
        github.com/robfig/cron/cron.go:165 +0x57
created by github.com/robfig/cron.(*Cron).run
        github.com/robfig/cron/cron.go:199 +0x6f4
2019/02/18 14:34:38 [Info] [4234973553] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > context canceled
2019/02/18 14:34:40 [Info] [156492081] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2019/02/18 14:34:46 [Info] SSPanelPlugin: old node info xxxxx;xx;16;ws;;path=/v1|host=jd.hk 
2019/02/18 14:34:46 [Info] SSPanelPlugin: new node info xxxxx;xx;16;ws;;path=/v1|host=jd.hk
2019/02/18 14:34:46 cron: panic running job: assignment to entry in nil map
goroutine 63101 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc0045e05f0)
        github.com/robfig/cron/cron.go:161 +0xbc
panic(0xaff9c0, 0xcab450)
        /go/src/runtime/panic.go:513 +0x1b9
github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/Manager.(*Manager).Remove(...)
        github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/Manager/Manager.go:41
github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin.(*Panel).updateManager(0xc00008f210)
        github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/panel.go:99 +0x9ab
github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin.(*Panel).do(0xc00008f210, 0xc02c69b0c0, 0x429fe1)
        github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/panel.go:55 +0x2b
github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin.(*Panel).Start.func1()
        github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/panel.go:39 +0x2e
github.com/robfig/cron.FuncJob.Run(0xc00008f230)
        github.com/robfig/cron/cron.go:92 +0x25
github.com/robfig/cron.(*Cron).runWithRecovery(0xc0045e05f0, 0xcb1640, 0xc00008f230)
        github.com/robfig/cron/cron.go:165 +0x57
created by github.com/robfig/cron.(*Cron).run
        github.com/robfig/cron/cron.go:199 +0x6f4
2019/02/18 14:34:46 [Info] SSPanelPlugin: now begin to check users
```

**Comment by rico93** [comment]
@eeeeLeeee 我的锅，有map没有初始化造成的，已经在修复了，和测速适配 编译后更新

**Comment by rico93** [comment]
@eeeeLeeee dev支链这个问题已经修复，已经有编译版本，我测试一时间，没啥问题就发布

**Comment by lanjuli** [comment]
Start Service
Creating v2rayagent_v2ray_1 ... 
Creating v2rayagent_v2ray_1 ... error

ERROR: for v2rayagent_v2ray_1  Cannot start service v2ray: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\"": unknown

ERROR: for v2ray  Cannot start service v2ray: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\"": unknown
ERROR: Encountered errors while bringing up the project.

镜像有问题？@rico93

**Comment by rico93** [comment]
> Start Service
> Creating v2rayagent_v2ray_1 ...
> Creating v2rayagent_v2ray_1 ... error
> 
> ERROR: for v2rayagent_v2ray_1 Cannot start service v2ray: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused "read init-p: connection reset by peer"": unknown
> 
> ERROR: for v2ray Cannot start service v2ray: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused "read init-p: connection reset by peer"": unknown
> ERROR: Encountered errors while bringing up the project.
> 
> 镜像有问题？@rico93

你是是啥系统啊 我这里没问题啊

**Comment by lanjuli** [comment]
> > 启动服务
> > 创建v2rayagent_v2ray_1 ... 
> > 创建v2rayagent_v2ray_1 ...错误
> > 错误：对于v2rayagent_v2ray_1无法启动服务v2ray：OCI运行时创建失败：container_linux.go：344：启动容器进程导致“process_linux.go：297：从管道导致最终子进程的pid”读取init-p：连接由对等重置“ “：未知
> > 错误：对于v2ray无法启动服务v2ray：OCI运行时创建失败：container_linux.go：344：启动容器进程导致“process_linux.go：297：从管道导致最终子进程的pid”读取init-p：连接由对等重置“ “：未知
> > 错误：在启动项目时遇到错误。
> > 镜像有问题？@ rico93
> 
> 你是是啥系统啊我这里没问题啊

centos7，用的一键脚本，启动镜像就报错

**Comment by rico93** [comment]
@lanjuli 测试正常 docker_caddy

**Comment by rico93** [comment]
@lanjuli 务必确保 你的系统虚拟环境能跑docker。 /(ㄒoㄒ)/~~ 我这里是aws centos7 测试

**Comment by lanjuli** [comment]
> @lanjuli测试正常docker_caddy

找到问题了，与CentOS 7支持安装锐速的内核3.10.0-327.el7.x86_64不兼容，我通过升级内核解决了。
看来只能用bbr了😂

**Comment by rico93** [comment]
@lanjuli 好的。。吓我一跳，以为今天刚写的就233了。 现在已经支持测速上报。 基本完成了

**Comment by eeeeLeeee** [comment]
@lanjuli 是docker和内核的兼容问题。建议使用正常版本的内核

**Comment by lanjuli** [comment]
> @lanjuli是搬运工和内核的兼容问题。建议使用正常版本的内核

知道了，我找到这个问题了

**Comment by lanjuli** [comment]
> @lanjuli好的..吓我一跳，以为今天刚写的就233了。现在已经支持测速上报。基本完成了

那我之前安装好的就用脚本更新下镜像就OK了？

**Comment by rico93** [comment]
@lanjuli 你用 docker-compose down && docker-compose pull && docker-compose up -d
