### ISSUE TITLE
请教两个 checkRate 参数的作用

### ISSUE THREAD

**Issue by dongriljf** [rico93/v2ray-sspanel-v3-mod_Uim-plugin#12]
这两个参数搞不清楚，如下 :
   "checkRate": 60,
    "SpeedTestCheckRate": 6,
请问这两个参数的单位是什么，作用是什么。

**Comment by rico93** [comment]
第一个是分，第二个是时。 第一个是用来和面板通讯上报用户流量ip的时间间隔，第二个是测速时间间隔
