### ISSUE TITLE
v2ray用不了

### ISSUE THREAD

**Issue by mathsning** [rico93/v2ray-sspanel-v3-mod_Uim-plugin#13]
v2ray已设置好，端口没问题，节点地址格式也按要求，sspanel中节点状态已显示绿色，ios shadowrocket中ping也能通，但没能翻出去，google用不了。对接节点类型为shadowsocks时正常

**Comment by rico93** [comment]
O__O "… 请上报log

**Comment by mathsning** [comment]
2019/06/08 18:14:06 [Error] SSPanelPlugin: SSPanelPlugin: Can't get data from server or the  data is not as expected current url: https://www.XXXXX.com  current md5 5818e9bb41d658fd77dfaef4cac12345

**Comment by rico93** [comment]
收费版本啊，当然得付费呀

**Comment by rico93** [comment]
请立即付，费感谢支持

**Comment by mathsning** [comment]
难怪。我对接过是显示绿色的，因不能用删掉了。为了看log再对接死活不显示绿色，原来用了收费版本。

**Comment by mathsning** [comment]
大神，给个免费版本试试吧

**Comment by rico93** [comment]
O__O  抱歉，我现在没有免费版本

**Comment by rico93** [comment]
需要联系使用[bot购买](https://t.me/Rico_V2_bot))
