### ISSUE TITLE
v2ray后端无法连接

### ISSUE THREAD

**Issue by ckyun06** [rico93/v2ray-sspanel-v3-mod_Uim-plugin#14]
部署后端后无法连接 
运行日志卡在
A unified platform for anti-censorship.

wiki看的有点懵逼 好像是config下这两段配置问题 
贴上config.json 两段配置文件
`"inbounds": [{
    "listen": "127.0.0.1",
    "port": 2333,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },`
` "sspanel": {
    "nodeid": 3,
    "checkRate": 60,
    "SpeedTestCheckRate": 6,
    "panelUrl": "http://v.test.cn(已修改为面板地址)",
    "panelKey": "NimaQu",
    "downWithPanel": 1,
    "mu_regex":  "%5m%id.%suffix",
    "mu_suffix": "microsoft.com",
    "mysql": {
      "host": "https://bing.com",
      "port": 3306,
      "user": "demo_user",
      "password": "demo_dbpassword",
      "dbname": "demo_dbname"
    },
    "paneltype": 0,
    "usemysql": 0
  }
}
`

**Comment by ckyun06** [comment]
前后端非一台vps

**Comment by rico93** [comment]
这个看起来没问题啊
