### ISSUE TITLE
是不是我哪里没弄对，内存被占满了

### ISSUE THREAD

**Issue by Kogami233** [rico93/v2ray-sspanel-v3-mod_Uim-plugin#3]
![qq 20190308201207](https://user-images.githubusercontent.com/28003549/54028040-90d60100-41de-11e9-8cc9-d526b0ac99d6.png)
重装过也是一样  求指点  谢谢_(:з)∠)_

**Comment by rico93** [comment]
额 怎么说，能贴你的 配置么，面板的配置。 然后用户数量。 不方便公开可以 tg ricobb 找我
