### ISSUE TITLE
tls (nginx 提供) 地址怎么填？

### ISSUE THREAD

**Issue by dongriljf** [rico93/v2ray-sspanel-v3-mod_Uim-plugin#6]
Caddy tls 的例子是
xxxxx.com;0;16;tls;ws;path=/v2ray|host=Caddy tls地址|inside_port=10550
如果是 nginx 呢，应该怎么配置？（nginx 异步并非性能好一些，想尽量发挥小鸡鸡的性能）

**Comment by dongriljf** [comment]
是不是可以改一下目前逻辑：
如果外部端口不是 0，则监听 0.0.0.0:外部端口，此时 inside_port 弃用。改成不要弃用。当两者同时出现就是弃用外部端口，意思是只有外部端口时inside_port=外部端口

外部端口在前端是给客户导入到客户端的唯一端口。因为客户端不需要知道inside_port ，反正是 nginx 反代到v2ray的端口。这样nginx 应该就可以用了。

**Comment by dongriljf** [comment]
host=Caddy tls地址 理解错误
原来是指服务器路径 好吧，就是剩下客户端 把端口认成 0 的问题。

**Comment by rico93** [comment]
0的时候，可以加outside_port 来覆盖

**Comment by rico93** [comment]
我自己维护的版 默认是443 会覆盖port

**Comment by dongriljf** [comment]
我发现套CF的时候SSL有错误，几分钟后会断线。不套CF就没事？

**Comment by GeekQu** [comment]
wiki 已更新，建议使用 <https://github.com/rico93/ss-panel-v3-mod_Uim>。

- 若 outside_port 不存在且端口为 0 或为空，则 PHP 端在生成订阅的时候会输出 port 为 443。
- 若 outside_port 存在，则 PHP 端会在生成订阅时候使用 outside_port 覆盖 port **。

**Comment by dongriljf** [comment]
|server=服务器ip是设置好的了 CF SSL full 和严格模式都试过了各种组合。

**Comment by rico93** [comment]
尝试把host指向同样的域名(而不是bing.com） 试试

**Comment by dongriljf** [comment]
你说的数据库对接，嗯，我数据库和API都试过，只要不套CF都能前后端正常使用。
我的是ws+tls 用nginx反代网站伪装。面板地址的host本来是网址伪装，字符串任填一般是填网址，不填也能用,都有真网站就没必要填伪装了。
但套cf 就会
SSPanelPlugin: json: cannot unmarshal string into Go struct field NodeinfoResponse.data of type model.NodeInfo 
initial system出现几次就一般过3分钟面板就检测到了，状态由绿色变成红叹号了
这说明后端和客户端通讯没问题，是前端和后端隔了cf无法通讯。前端对后端失去控制后端却没停。然后检查上网，奇怪的是油管能上，fb，github.com不能上，原来不套CF都能上。
开始我觉得以为是证书问题，折腾了一下，现在觉得其实是面板和后端通讯的问题。没用前端的那种v2ray做同样的ws+tls 用nginx反代网站伪装就没这种问题。不知道是不是其他前端才有的问题。

**Comment by dongriljf** [comment]
感觉server参数好像没起到面板和后端直连的作用。

**Comment by GeekQu** [comment]
您需要重新查阅一下 Wiki 中的节点地址格式第一个分号之前的内容。

**Comment by dongriljf** [comment]
就是域名啊，这个会错吗？没用前端的时候都是正常的。不套cf的CDN（只用cf的DNS）前端后端客户端所有状态是正常的。后端正常上传用户信息到数据库什么的。客户端正常通讯。什么网都能上。套上CDN后才有问题，节点状态变红；不套CDN，不用操作后端主机，过几分钟自动检测正常，面板节点状态又是绿的了。
